server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: password

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 31201212038-7qhs1pgndud0njirnkm79747r853nj3h.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 1570280473334180
            client-secret: aa0102b064d89f6cf3a8ef683cea1355
            scope:
              - email
              - public_profile

          naver:
            client-id: Pvp1Mr6p26SVH_3EdLOb
            client-secret: YbEm3pzv5K
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response